// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Testing1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testing1() {
    // Test name: Testing 1
    // Step # | name | target | value
    // 1 | open | /login | 
    driver.Navigate().GoToUrl("http://localhost:3000/login");
    // 2 | setWindowSize | 1536x816 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 816);
    // 3 | type | id=email | kale@gmail.com
    driver.FindElement(By.Id("email")).SendKeys("kale@gmail.com");
    // 4 | type | id=password | kale@123
    driver.FindElement(By.Id("password")).SendKeys("kale@123");
    // 5 | click | id=password | 
    driver.FindElement(By.Id("password")).Click();
    // 6 | click | css=.MuiButton-containedPrimary | 
    driver.FindElement(By.CssSelector(".MuiButton-containedPrimary")).Click();
    // 7 | mouseOver | css=.css-51dco4-MuiButtonBase-root-MuiButton-root | 
    {
      var element = driver.FindElement(By.CssSelector(".css-51dco4-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 8 | click | css=.css-51dco4-MuiButtonBase-root-MuiButton-root | 
    driver.FindElement(By.CssSelector(".css-51dco4-MuiButtonBase-root-MuiButton-root")).Click();
    // 9 | mouseOut | css=.css-51dco4-MuiButtonBase-root-MuiButton-root | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 10 | mouseOver | css=.css-51dco4-MuiButtonBase-root-MuiButton-root | 
    {
      var element = driver.FindElement(By.CssSelector(".css-51dco4-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 11 | click | css=.css-51dco4-MuiButtonBase-root-MuiButton-root | 
    driver.FindElement(By.CssSelector(".css-51dco4-MuiButtonBase-root-MuiButton-root")).Click();
    // 12 | mouseOut | css=.css-51dco4-MuiButtonBase-root-MuiButton-root | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 13 | mouseOver | css=.css-hwifar-MuiButtonBase-root-MuiButton-root | 
    {
      var element = driver.FindElement(By.CssSelector(".css-hwifar-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 14 | click | css=.css-hwifar-MuiButtonBase-root-MuiButton-root | 
    driver.FindElement(By.CssSelector(".css-hwifar-MuiButtonBase-root-MuiButton-root")).Click();
    // 15 | mouseOut | css=.css-hwifar-MuiButtonBase-root-MuiButton-root | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 16 | mouseOver | css=.MuiButton-outlined | 
    {
      var element = driver.FindElement(By.CssSelector(".MuiButton-outlined"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 17 | click | css=.MuiButton-outlined | 
    driver.FindElement(By.CssSelector(".MuiButton-outlined")).Click();
    // 18 | mouseOut | css=.MuiButton-outlined | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 19 | mouseOver | css=.MuiButton-textPrimary | 
    {
      var element = driver.FindElement(By.CssSelector(".MuiButton-textPrimary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 20 | click | css=.MuiButton-textPrimary | 
    driver.FindElement(By.CssSelector(".MuiButton-textPrimary")).Click();
    // 21 | mouseOver | css=.css-hwifar-MuiButtonBase-root-MuiButton-root | 
    {
      var element = driver.FindElement(By.CssSelector(".css-hwifar-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 22 | click | css=.css-hwifar-MuiButtonBase-root-MuiButton-root | 
    driver.FindElement(By.CssSelector(".css-hwifar-MuiButtonBase-root-MuiButton-root")).Click();
    // 23 | mouseOut | css=.css-hwifar-MuiButtonBase-root-MuiButton-root | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 24 | click | css=.MuiButton-outlined | 
    driver.FindElement(By.CssSelector(".MuiButton-outlined")).Click();
    // 25 | mouseDown | id=:rl: | 
    {
      var element = driver.FindElement(By.Id(":rl:"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    // 26 | mouseUp | css=#menu- > .MuiBackdrop-root | 
    {
      var element = driver.FindElement(By.CssSelector("#menu- > .MuiBackdrop-root"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    // 27 | click | css=body | 
    driver.FindElement(By.CssSelector("body")).Click();
    // 28 | click | css=#\3Arn\3A > .MuiButtonBase-root:nth-child(2) | 
    driver.FindElement(By.CssSelector("#\\3Arn\\3A > .MuiButtonBase-root:nth-child(2)")).Click();
    // 29 | click | id=:rr: | 
    driver.FindElement(By.Id(":rr:")).Click();
    // 30 | type | id=:rr: | 50
    driver.FindElement(By.Id(":rr:")).SendKeys("50");
    // 31 | click | id=:rt: | 
    driver.FindElement(By.Id(":rt:")).Click();
    // 32 | type | id=:rt: | Testing Automation
    driver.FindElement(By.Id(":rt:")).SendKeys("Testing Automation");
    // 33 | click | css=.MuiDialogActions-root | 
    driver.FindElement(By.CssSelector(".MuiDialogActions-root")).Click();
    // 34 | mouseOver | css=.MuiButton-containedPrimary:nth-child(2) | 
    {
      var element = driver.FindElement(By.CssSelector(".MuiButton-containedPrimary:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 35 | click | css=.MuiButton-containedPrimary:nth-child(2) | 
    driver.FindElement(By.CssSelector(".MuiButton-containedPrimary:nth-child(2)")).Click();
    // 36 | mouseOut | css=.Mui-disabled | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 37 | mouseOver | css=.MuiAvatar-root | 
    {
      var element = driver.FindElement(By.CssSelector(".MuiAvatar-root"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 38 | click | css=.MuiAvatar-root | 
    driver.FindElement(By.CssSelector(".MuiAvatar-root")).Click();
    // 39 | mouseOut | css=.MuiAvatar-root | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 40 | click | css=.MuiMenuItem-root:nth-child(2) | 
    driver.FindElement(By.CssSelector(".MuiMenuItem-root:nth-child(2)")).Click();
    // 41 | type | id=email | kale@gmail.com
    driver.FindElement(By.Id("email")).SendKeys("kale@gmail.com");
    // 42 | type | id=password | kale@123
    driver.FindElement(By.Id("password")).SendKeys("kale@123");
    // 43 | click | id=email | 
    driver.FindElement(By.Id("email")).Click();
    // 44 | type | id=email | faisal@gmail.com
    driver.FindElement(By.Id("email")).SendKeys("faisal@gmail.com");
    // 45 | type | id=password | sara123
    driver.FindElement(By.Id("password")).SendKeys("tara123");
    // 46 | click | css=.MuiButton-containedPrimary | 
    driver.FindElement(By.CssSelector(".MuiButton-containedPrimary")).Click();
    // 47 | mouseOver | css=.css-51dco4-MuiButtonBase-root-MuiButton-root | 
    {
      var element = driver.FindElement(By.CssSelector(".css-51dco4-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 48 | click | css=.css-51dco4-MuiButtonBase-root-MuiButton-root | 
    driver.FindElement(By.CssSelector(".css-51dco4-MuiButtonBase-root-MuiButton-root")).Click();
    // 49 | mouseOut | css=.css-51dco4-MuiButtonBase-root-MuiButton-root | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 50 | click | css=.MuiButton-outlined | 
    driver.FindElement(By.CssSelector(".MuiButton-outlined")).Click();
    // 51 | mouseOver | css=.MuiButton-text | 
    {
      var element = driver.FindElement(By.CssSelector(".MuiButton-text"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 52 | click | css=.MuiButton-text | 
    driver.FindElement(By.CssSelector(".MuiButton-text")).Click();
    // 53 | mouseOut | css=.MuiButton-text | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 54 | mouseOver | css=.MuiAvatar-root > .MuiSvgIcon-root | 
    {
      var element = driver.FindElement(By.CssSelector(".MuiAvatar-root > .MuiSvgIcon-root"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 55 | click | css=.MuiAvatar-root > .MuiSvgIcon-root | 
    driver.FindElement(By.CssSelector(".MuiAvatar-root > .MuiSvgIcon-root")).Click();
    // 56 | mouseOut | css=.MuiAvatar-root > .MuiSvgIcon-root | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 57 | click | css=.MuiMenuItem-root:nth-child(2) | 
    driver.FindElement(By.CssSelector(".MuiMenuItem-root:nth-child(2)")).Click();
    // 58 | type | id=email | faisal@gmail.com
    driver.FindElement(By.Id("email")).SendKeys("faisal@gmail.com");
    // 59 | type | id=password | sara123
    driver.FindElement(By.Id("password")).SendKeys("sara123");
  }
}
